spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    env:
      enabled : true

info:
  app:
    version: '@project.version@'